### PR TITLE
Adding FEN to ChessPosition conversion

### PR DESCRIPTION
**Pull request by B4dT0bi**
Hi,

i've added the possibility to convert a FEN-String to a ChessPosition Object, so now the ChessBoardModel can also be initialized with a FEN-String.

regards Tobi

### CODE REVIEW

**Comment by alcibiade** [comment]
Thanks very much for the contribution.

I just have one point: I'd prefer to stick to using AssertJ for assertions in new tests:

`Assertions.assertThat(initialPositionAsFen).isEqualTo("rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1");`

Its is more flexible and  provides much more sensible output logs on error.

Could you submit a new request with all the new assertions in that form ?

**Comment by alcibiade** [comment]
Thanks a lot !

**Comment by B4dT0bi** [comment]
Hi,

i've modified the Test using Assertj and found an error which was not visible with the normal Assert o.O

regards Tobi

**Comment by alcibiade** [comment]
I have just released version 1.6.2 to the maven central repository which contains your code.

**Pull request merged**
